### PR TITLE
State Tools Collection

### PR DESCRIPTION
**Pull request by AurevoirXavier**

### CODE REVIEW

**Comment by flipchan** [comment]
@AurevoirXavier can we get some more documentation for this?

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier can we get some more documentation for this?

Of course! I've already created an issue for this #30.
I'm on vacation now. I'll finish that in around 3 days.

**Comment by AurevoirXavier** [comment]
Hi @flipchan.
The doc is updated. Check it [here](https://subalfred.hack.ink/user/cli/state.html).

Looking forward to your feedback.

**Comment by flipchan** [comment]
Sweeet! I will check it out, thanks a lot @AurevoirXavier

**Pull request merged**
